environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'
    - nodejs_version: '10'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
matrix:
  fast_finish: true
